import { Product, Order, Transaction, User, DashboardStats } from '@/types';

export const mockUser: User = {
  id: 'dist-001',
  email: 'distributor@example.com',
  name: 'Ram Sharma',
  distributorId: 'DIST-KTM-001',
  role: 'distributor',
};

export const mockProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Premium Rice',
    category: 'Grains',
    description: 'High-quality basmati rice, 25kg bag',
    pricePerUnit: 2500,
    availableQuantity: 500,
    unit: 'bag',
    imageUrl: '/images/rice.jpg',
  },
  {
    id: 'prod-002',
    name: 'Cooking Oil',
    category: 'Oils',
    description: 'Refined sunflower oil, 1L bottle',
    pricePerUnit: 180,
    availableQuantity: 1000,
    unit: 'bottle',
    imageUrl: '/images/oil.jpg',
  },
  {
    id: 'prod-003',
    name: 'Wheat Flour',
    category: 'Flour',
    description: 'Premium wheat flour, 10kg bag',
    pricePerUnit: 800,
    availableQuantity: 300,
    unit: 'bag',
    imageUrl: '/images/flour.jpg',
  },
  {
    id: 'prod-004',
    name: 'Lentils (Dal)',
    category: 'Pulses',
    description: 'Mixed lentils, 5kg bag',
    pricePerUnit: 650,
    availableQuantity: 200,
    unit: 'bag',
    imageUrl: '/images/dal.jpg',
  },
  {
    id: 'prod-005',
    name: 'Tea Powder',
    category: 'Beverages',
    description: 'Premium tea powder, 500g pack',
    pricePerUnit: 450,
    availableQuantity: 150,
    unit: 'pack',
    imageUrl: '/images/tea.jpg',
  },
  {
    id: 'prod-006',
    name: 'Sugar',
    category: 'Sweeteners',
    description: 'Refined white sugar, 50kg bag',
    pricePerUnit: 4200,
    availableQuantity: 100,
    unit: 'bag',
    imageUrl: '/images/sugar.jpg',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ord-001',
    distributorId: 'DIST-KTM-001',
    items: [
      {
        productId: 'prod-001',
        productName: 'Premium Rice',
        quantity: 10,
        pricePerUnit: 2500,
        totalPrice: 25000,
      },
      {
        productId: 'prod-002',
        productName: 'Cooking Oil',
        quantity: 50,
        pricePerUnit: 180,
        totalPrice: 9000,
      },
    ],
    totalAmount: 34000,
    status: 'delivered',
    orderDate: new Date('2024-01-15'),
    expectedDeliveryDate: new Date('2024-01-20'),
    notes: 'Regular monthly order',
  },
  {
    id: 'ord-002',
    distributorId: 'DIST-KTM-001',
    items: [
      {
        productId: 'prod-003',
        productName: 'Wheat Flour',
        quantity: 20,
        pricePerUnit: 800,
        totalPrice: 16000,
      },
    ],
    totalAmount: 16000,
    status: 'processing',
    orderDate: new Date('2024-01-18'),
    expectedDeliveryDate: new Date('2024-01-23'),
  },
  {
    id: 'ord-003',
    distributorId: 'DIST-KTM-001',
    items: [
      {
        productId: 'prod-004',
        productName: 'Lentils (Dal)',
        quantity: 15,
        pricePerUnit: 650,
        totalPrice: 9750,
      },
      {
        productId: 'prod-005',
        productName: 'Tea Powder',
        quantity: 30,
        pricePerUnit: 450,
        totalPrice: 13500,
      },
    ],
    totalAmount: 23250,
    status: 'pending',
    orderDate: new Date('2024-01-20'),
    expectedDeliveryDate: new Date('2024-01-25'),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-001',
    distributorId: 'DIST-KTM-001',
    orderId: 'ord-001',
    type: 'order',
    amount: -34000,
    currency: 'NPR',
    description: 'Order payment for rice and oil',
    date: new Date('2024-01-15'),
    status: 'completed',
    reference: 'PAY-001',
  },
  {
    id: 'txn-002',
    distributorId: 'DIST-KTM-001',
    orderId: 'ord-002',
    type: 'order',
    amount: -16000,
    currency: 'NPR',
    description: 'Order payment for wheat flour',
    date: new Date('2024-01-18'),
    status: 'completed',
    reference: 'PAY-002',
  },
  {
    id: 'txn-003',
    distributorId: 'DIST-KTM-001',
    type: 'payment',
    amount: 5000,
    currency: 'NPR',
    description: 'Account credit adjustment',
    date: new Date('2024-01-10'),
    status: 'completed',
    reference: 'ADJ-001',
  },
  {
    id: 'txn-004',
    distributorId: 'DIST-KTM-001',
    orderId: 'ord-003',
    type: 'order',
    amount: -23250,
    currency: 'NPR',
    description: 'Order payment for lentils and tea',
    date: new Date('2024-01-20'),
    status: 'pending',
    reference: 'PAY-003',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalOrders: 15,
  pendingOrders: 3,
  completedOrders: 12,
  totalSpent: 485000,
  thisMonthSpent: 73250,
  availableProducts: 6,
};

